name: chart/axis-bottom
desc: |
  The chart/axis-bottom element is used to draw a labelled 'bottom axis'.

reference: |
  (chart/axis-bottom <options>)

option_summary: true

properties:
  - title: "Label Options"
    anchor: label-options
    inherit: ["elements/chart/axis", "label-options"]

  - title: "Scale Options"
    anchor: scale-options
    inherit: ["elements/chart/axis", "scale-options"]

  - title: "Title Options"
    anchor: title-options
    inherit: ["elements/chart/axis", "title-options"]

  - title: "Border Options"
    anchor: border-options
    inherit: ["elements/chart/axis", "border-options"]
