name: chart/scatterplot
example: charts-basic/scatterplot
desc: |
  The `chart/scatterplot` element is a helper element for creating scatterplots.

reference: |
  (chart/scatterplot <options>)

option_summary: true

properties:

  - title: "Point Options"
    anchor: point-options
    inherit: ["elements/plot/points", "point-options"]

  - title: "Label Options"
    anchor: label-options
    inherit: ["elements/plot/points", "label-options"]

  - title: "Scale Options"
    anchor: scale-options
    inherit: ["elements/plot", "scale-options"]

  - title: "Axis Options"
    anchor: axis-options
    inherit: ["elements/plot", "axis-options"]

  - title: "Layout Options"
    anchor: layout-options
    inherit: ["elements/layout/box", "layout-options"]

  - title: "Background Options"
    anchor: background-options
    inherit: ["elements/layout/box", "background-options"]

  - title: "Border Options"
    anchor: border-options
    inherit: ["elements/layout/box", "border-options"]
