---

documentation:
  -
    title: "Using FnordMetric"
    pages:
      -
        title: "Getting Started"
        url: "/"
        file: "getting_started"
      -
        title: "Installation"
        url: "/installation"
        file: "installation"
      -
        title: "Getting Started: FnordMetric Server"
        url: "/getting_started/fnordmetric-server"
        file: "/getting_started_with_fnordmetric_server"
      -
        title: "Getting Started: ChartSQL"
        url: "/getting_started/fnordmetric-cli"
        file: "/getting_started_with_fnordmetric_cli"

  -
    title: "Query Language (ChartSQL)"
    pages:
      -
        title: "Introduction"
        url: "/chartsql/introduction"
        file: "chartsql_introduction"
      -
        title: "Drawing Charts"
        url: "/chartsql/draw_statement"
        file: "chartsql_draw"
      -
        title: "Time-window Aggregations"
        url: "/chartsql/timewindow_aggregations"
        file: "chartsql_timewindow"
      -
        title: "External Data Sources"
        url: "/chartsql/external_data_sources"
        file: "chartsql_import"
      -
        title: "Built-in Functions"
        url: "/chartsql/built_in_functions"
        file: "chartsql_builtins"
      -
        title: "Syntax Reference"
        url: "/chartsql/syntax_reference"
        file: "chartsql_syntax_reference"

  -
    title: "Collecting Data"
    pages:
      -
        title: "Collecting Metrics"
        url: "/metricdb/collecting_metrics"
        file: "metricdb_collecting_metrics"
      -
        title: "Storage Backends"
        url: "/metricdb/storage_backends"
        file: "metricdb_storage_backends"
      -
        title: "Sending data via HTTP"
        url: "/metricdb/sending_data_via_http"
        file: "sending_data_via_http"
      -
        title: "Sending data via statsd"
        url: "/metridb/statsd_interface"
        file: "metricdb_statsd_interface"
      -
        title: "Retention Policies"
        url: "/query_language/reference"
      -
        title: "Included agents"
        url: "/query_language/reference"

  -
    title: "Building Dashboards"
    pages:
      -
        title: "Getting started with Dashboards"
        url: "/html5_dashboards"
        file: "html5_dashboards"
      -
        title: "HTML5 API Reference"
        url: "/html5_api_reference"
        file: "html5_api_reference"

  -
    title: "Customizing Charts"
    pages:
      -
        title: "Axis styles"
        url: "/query_language/reference"
      -
        title: "Legend styles"
        url: "/query_language/reference"
      -
        title: "Point and Line styles"
        url: "/query_language/reference"
      -
        title: "Line Charts"
        url: "/query_language/reference"
      -
        title: "Point Charts"
        url: "/query_language/reference"
      -
        title: "Area Charts"
        url: "/query_language/reference"
      -
        title: "Bar Charts"
        url: "/query_language/reference"
      -
        title: "Interactive Charts"
        url: "/query_language/reference"
      -
        title: "Styles / Themes"
        url: "/query_language/reference"

  -
    title: "FnordMetric APIs &amp Clients"
    pages:
      -
        title: "FnordMetric HTTP API"
        url: "/http_api"
        file: "http_api"
      -
        title: "FnordMetric for JavaScript"
        url: "/query_language/reference"
      -
        title: "FnordMetric for Ruby (on Rails)"
        url: "/query_language/reference"


  -
    title: "Hacking"
    pages:
      -
        title: "Support"
        url: "/support"
        file: "support"
      -
        title: "Contributing"
        url: "/contributing"
        file: "contributing"
      -
        title: "License"
        url: "/license"
        file: "license"

examples:

  -
    title: "Line Charts"
    dir: "linecharts"
    examples:
      -
        title: "Simple timeseries line chart"
        file: "simple_lines"
        url: "/linecharts/simple_lines"
        thumb: "/img/examples_simple_lines.png"
      -
        title: "Lines with points"
        file: "lines_with_points"
        url: "/linecharts/lines_with_points"
        thumb: "/img/examples_lines_with_points.png"
      -
        title: "Explicit range/domain"
        file: "explicit_domain"
        url: "/linecharts/explicit_domain"
        thumb: "/img/examples_explicit_domain.png"
      -
        title: "Lines with data labels"
        file: "lines_with_labels"
        url: "/linecharts/lines_with_labels"
        thumb: "/img/examples_lines_with_labels.png"
      -
        title: "Multiple Y Axes"
        file: "multiple_y_axes"
        url: "/linecharts/multiple_y_axes"
        thumb: "/img/examples_multiple_y_axes.png"
      -
        title: "Logarithmic domain"
        file: "logarithmic_domain"
        url: "/linecharts/logarithmic_domain"
        thumb: "/img/examples_logarithmic_domain.png"
#      -
#        title: "Line and Point styles"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
      -
        title: "Data with irregular intervals"
        file: "irregular_intervals"
        url: "/linecharts/irregular_data"
        thumb: "/img/examples_irregular_data.png"
#      -
#        title: "Lines with missing data"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
      -
        title: "Inverted Axis"
        file: "inverted_axis"
        url: "/linecharts/inverted_axis"
        thumb: "/img/examples_inverted_axis.png"

  -
    title: "Area Charts"
    dir: "areacharts"
    examples:
      -
        title: "Simple area chart"
        file: "simple_area"
        url: "/areacharts/simple_area"
        thumb: "/img/examples_simple_area.png"
      -
        title: "Area with borders/points"
        file: "area_with_points"
        url: "/areacharts/area_with_points"
        thumb: "/img/examples_area_with_points.png"
#      -
#        title: "Stacked areas"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
      -
        title: "Area ranges"
        file: "area_ranges"
        url: "/areacharts/area_ranges"
        thumb: "/img/examples_area_ranges.png"

  -
    title: "Bar Charts"
    dir: "barcharts"
    examples:
      -
        title: "Vertical bar chart, multiple series"
        file: "vertical_bars"
        url: "/barcharts/vertical_bars"
        thumb: "/img/examples_vertical_bars.png"
      -
        title: "Horizontal bar chart with labels"
        file: "horizontal_bars"
        url: "/barcharts/horizontal_bars"
        thumb: "/img/examples_horizontal_bars.png"
      -
        title: "Stacked Bar Chart"
        file: "stacked_bars"
        url: "/barcharts/stacked_bars"
        thumb: "/img/examples_stacked_bars.png"
      -
        title: "Vertical range bars"
        file: "vertical_ranges"
        url: "/barcharts/vertical_ranges"
        thumb: "/img/examples_vertical_ranges.png"
      -
        title: "Horizontal range bars"
        file: "horizontal_ranges"
        url: "/barcharts/horizontal_ranges"
        thumb: "/img/examples_horizontal_ranges.png"
#      -
#        title: "Histogram"
#        file: "horizontal_bars"
      -
        title: "Bars with negative values"
        file: "negative_values"
        url: "/barcharts/negative_values"
        thumb: "/img/examples_negative_values.png"

  -
    title: "Bubble &amp; Scatter Charts"
    dir: "barcharts"
    examples:
      -
        title: "Simple bubble chart"
        file: "simple_bubble_chart"
        url: "/pointcharts/simple_bubbles"
        thumb: "/img/examples_simple_bubbles.png"
      -
        title: "Simple scatter chart"
        file: "simple_scatter_chart"
        url: "/pointcharts/simple_scatter"
        thumb: "/img/examples_simple_scatter.png"
      -
        title: "Point chart with data labels"
        file: "pointchart_with_labels"
        url: "/pointcharts/pointchart_with_labels"
        thumb: "/img/examples_pointchart_with_labels.png"
#      -
#        title: "Points with middle axis"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#
  -
    title: "Combined Charts"
    dir: "combined"
    examples:
      -
        title: "Bars and Lines"
        file: "bars_and_lines"
        url: "/combined/barsandlines"
        thumb: "/img/examples_barsandlines.png"
#      -
#        title: "Lines with error bars"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
      -
        title: "Areas with lines"
        file: "arearange_and_line"
        url: "/combined/arearange_and_line"
        thumb: "/img/examples_arearange_and_line.png"

#  -
#    title: "Axis &amp Legend"
#    dir: "styles"
#    examples:
#      -
#        title: "Rotated axis labels"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#      -
#        title: "Axis styles"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#      -
#        title: "Horizontal grid"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#      -
#        title: "Horizontal &amp; Vertical grid"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#      -
#        title: "Legend outside, Axes inside"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"

#  -
#    title: "Custom styles"
#    dir: "styles"
#    examples:
#      -
#        title: "Default Style"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#      -
#        title: "Dark Style"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#
#  -
#    title: "Dashboards"
#    dir: "dashboards"
#    examples:
#      -
#        title: "Web application"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"

#  * horizontal with labels outside
#  * horizontal with labels inside

