---


sitemap:

  fnordmetric_ui:
    -
      title: "Getting Started"
      url: "/ui_index"
    -
      title: "API Reference"
      url: "/ui_html5_api"
    -
      title: "Examples"
      url: "/ui_examples"

  fnordmetric_classic:
    -
      title: "Getting Started"
      url: "/classic_index"
    -
      title: "Running FnordMetric"
      url: "/classic_running_fm"
    -
      title: "Sending Data"
      url: "/classic_sending_data"
    -
      title: "Events and Gauges"
      url: "/classic_event_handlers"
    -
      title: "Widgets"
      url: "/classic_widgets"
    -
      title: "Plugins"
      url: "/classic_plugins"
    -
      title: "Examples"
      url: "/classic_examples"
    -
      title: "Hacking"
      url: "/classic_hacking"


  fnordmetric_enterprise:
    -
      title: "Getting Started"
      url: "/enterprise_index"
    -
      title: "API Reference"
      url: "/enterprise_api_reference"
    -
      title: "HTTP API"
      url: "/enterprise_http_api"
    -
      title: "Configuration"
      url: "/enterprise_usage"
    #-
    #  title: "Clients"
    #  url: "/enterprise_usage"
    #-
    #  title: "Examples"
    #  url: "/enterprise_examples"


